### ISSUE TITLE
Change validation ⚠ icon to something less scary

### ISSUE THREAD

**Issue by demanrisu** [StirfireStudios/Jacquard#16]
The ⚠ icon implies something's wrong - a field being empty shouldn't be a cause for alarm, maybe a lightened ℹ icon would be more suitable?

**Comment by lordmortis** [comment]
I feel like the things that aren't validating should be handled better. What errors are you getting?

**Comment by demanrisu** [comment]
Things like an `tags` or `section` attribute field being empty cause the editor to bring up a warning. Is there a list of things that generate warnings?

**Comment by lordmortis** [comment]
Yeah, I feel like if the user is doing something valid, it shouldn't generate  warning - so we need to fix that too. 

What [material-ui](https://material.io/tools/icons/?style=baseline) icon should we use?

**Comment by demanrisu** [comment]
Ideally I think we have it off by default, and allow users to switch on
minor validation icons like this in case they're working on something that
depends on sections or tags?

**Comment by lordmortis** [comment]
On the spurious warnings:

So right now those warnings are being generated by what i consider to be a bug - the thing that builds the yarn file in the editor (that gets thrown through the parser) isn't excluding empty tags.

The parser generates a warning on those tags because I think that if you've got a tag and it's empty in a yarn file you should be told "hey, are you sure you didn't mean to put something here?"

So I want to fix this and they'll go away. Simultaneously, if we need to change warning icons, we should select one now while it's easy to generate warnings :D

**Comment by demanrisu** [comment]
Maybe label_off?

**Comment by lordmortis** [comment]
bah, i can't use that one - it's not in there yet, how about `HelpOutline` ?

**Comment by lordmortis** [comment]
Check release [0.6.0](https://github.com/StirfireStudios/Jacquard/releases/edit/0.6.0)
